CREATE OR REPLACE TABLE DAFT_TRANSFORMED(
    ID INT,
    ADDRESS STRING,
    COUNTY STRING,
    SALETYPE STRING,
    PROPERTYTYPE STRING,
    BER STRING,
    BATHROOMS STRING,
    BEDROOMS STRING,
    CATEGORY STRING,
    MONTHLY_PRICE STRING,
    PRICE STRING,
    LATITUDE FLOAT,
    LONGITUDE FLOAT,
    PUBLISH_DATE STRING,
    AGENT_ID INT,
    AGENT_BRANCH STRING,
    AGENT_NAME STRING,
    AGENT_SELLER_TYPE STRING,
    PRIMARY KEY(ID));

COPY INTO DAFT_TRANSFORMED
    FROM @AWS_DAFT
    FILES = ('preprocessed_data.csv')
     FILE_FORMAT = (
                    TYPE=CSV,
                    SKIP_HEADER=1,
                    FIELD_DELIMITER=',',
                    TRIM_SPACE=FALSE,
                    FIELD_OPTIONALLY_ENCLOSED_BY='"',
                    DATE_FORMAT=AUTO,
                    TIME_FORMAT=AUTO,
                    TIMESTAMP_FORMAT=AUTO
                )
ON_ERROR=ABORT_STATEMENT;